/*
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS room_status;
DROP TABLE IF EXISTS room_type;
DROP TABLE IF EXISTS room_capacity;
*/

CREATE TABLE IF NOT EXISTS room_status (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS room_type (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS room_capacity (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS rooms (
id BIGSERIAL PRIMARY KEY,
room_number TEXT UNIQUE NOT NULL,
room_type_id BIGINT NOT NULL REFERENCES room_type,
room_capacity_id BIGINT NOT NULL REFERENCES room_capacity,
price DECIMAL NOT NULL,
room_status_id BIGINT NOT NULL REFERENCES room_status,
deleted BOOLEAN NOT NULL DEFAULT FALSE
);